### ISSUE TITLE
"Index out of bounds" when placeholder is repeated 

### ISSUE THREAD

**Issue by keynmol** [armanbilge/porcupine#30]
May be I'm holding it wrong, but here's the repro:

```scala
//> using lib "com.armanbilge::porcupine::0.0.1"

import porcupine.*, Codec.*
import cats.effect.*

object app extends IOApp.Simple:
  def run =
    Database.open[IO]("test.db").use { db =>
      db.execute(
        sql"drop table if exists help;".command
      ) *>
        db.execute(
          sql"create table if not exists help(id integer primary key not null, test text)".command
        ) *>
        db.unique(
          sql"insert into help(id, test) values ($integer, $text) returning id * 100"
            .query(integer),
          25L -> "howdy"
        ).flatMap(IO.println) *> // OK
        db.unique(
          sql"begin; update help set test = 'bye' where id = $integer; insert into help(id, test) values ($integer, $text); commit;".command,
          (25L, 25L, "howdy")
        ).flatMap(IO.println) // NOT OK
    }
```

Output:

```
2500
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at org.sqlite.core.CorePreparedStatement.batch(CorePreparedStatement.java:105)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.setLong(JDBC3PreparedStatement.java:299)
	at porcupine.DatabasePlatform$$anon$1$$anon$2.cursor$$anonfun$1$$anonfun$1(dbplatform.scala:50)
	at main$ @ app$.main(test.scala:6)
	at main$ @ app$.main(test.scala:6)
	at main$ @ app$.main(test.scala:6)


```

**Comment by armanbilge** [comment]
Woops! thanks 🤔

**Comment by keynmol** [comment]
Additionally, if you have any recommendations how to do this particular query (same value in two places in a query) in a better way in Skunk/Porcupine style - let me know.

**Comment by armanbilge** [comment]
Ok, it seems like it needs to be split into multiple execute statements? Something like this.
```scala
      db.execute(sql"begin transaction".command) *>
        db.execute(sql"update help set test = 'bye' where id = $integer".command, 25L) *>
        db.execute(sql"insert into help(id, test) values ($integer, $text)".command, (26L, "howdy")) *>
        db.execute(sql"commit".command)
```

**Comment by keynmol** [comment]
What about this though?

```scala
        db.unique(
          sql"insert into help(id, test) values ($integer + $integer, 'yo')".command,
          (25L, 25L)
        ).flatMap(IO.println) // NOT OK
```

```
java.util.NoSuchElementException
	at porcupine.AbstractStatement.unique$$anonfun$2$$anonfun$1(db.scala:120)
	at flatMap @ porcupine.AbstractStatement.unique$$anonfun$2(db.scala:123)
	at main$ @ app$.main(test.scala:6)
	at main$ @ app$.main(test.scala:6)
	at main$ @ app$.main(test.scala:6)
```

**Comment by armanbilge** [comment]
That query doesn't return any results, so `unique` will fail.

**Comment by armanbilge** [comment]
Probably related to this?

> It's not incompatible with other implementations. sqlite prepared statements can only contain a single SQL statement. This is a restriction of sqlite itself, not better-sqlite3. The default behavior is for it to compile successfully, although executing the prepared statement will silently ignore any SQL beyond the first statement in the source SQL.

- https://github.com/WiseLibs/better-sqlite3/issues/40#issuecomment-310722824

**Comment by keynmol** [comment]
Hmm.

I guess I'll just something like

```scala
  extension (db: Database[IO])
    def transact[A](a: IO[A]) =
      import Outcome.*
      db.execute(sql"begin transaction".command) *>
        a.guaranteeCase {
          case Succeeded(_) => db.execute(sql"commit".command)
          case _            => db.execute(sql"rollback".command)

        }

```

for now - I struggle to find this restriction in sqlite's own docs (https://www.sqlite.org/c3ref/prepare.html)

**Comment by armanbilge** [comment]
> I struggle to find this restriction in sqlite's own docs

This part maybe.

> If pzTail is not NULL then *pzTail is made to point to the first byte past the end of the first SQL statement in zSql. These routines only compile the first statement in zSql, so *pzTail is left pointing to what remains uncompiled.

**Comment by keynmol** [comment]
Coming back to this...

```scala
db.execute(sql"begin transaction".command) *>
        a.guaranteeCase {
...
```

this isn't quite correct, is it? 

Because `*>` is not an atomic combinator, this can lead to transactions nesting, right? I didn't expect to see that on a single threaded environment, but here we are.

I wrapped tons more updates into transactions (because I'm seeing stale records, thought it'd help) - and I can now see errors like

```
    java.lang.RuntimeException: cannot start a transaction within a transaction
        at java.lang.StackTrace$.currentStackTrace$$anonfun$1(null)
        at java.lang.StackTrace$$$Lambda$2.applyVoid(null)
        at blocking @ porcupine.DatabasePlatform$$anon$1$$anon$2.porcupine$DatabasePlatform$$anon$1$$anon$2$$_$cursor$$anon
    fun$3(null)
        at blocking @ porcupine.DatabasePlatform.open$$anonfun$1(null)
        at main @ bindgen.web.internal.jobs.app.main(null)
        at flatMap @ porcupine.DatabasePlatform$$anon$1$$anon$2.porcupine$DatabasePlatform$$anon$1$$anon$2$$_$cursor$$anonf
    un$3(null)
        at void @ porcupine.DatabasePlatform$$anon$1.porcupine$DatabasePlatform$$anon$1$$anon$2$$_$cursor$$anonfun$2(null)
        at delay @ porcupine.DatabasePlatform$$anon$1$$anon$2.cursor(null)
        at main @ bindgen.web.internal.jobs.app.main(null)
        at main @ bindgen.web.internal.jobs.app.main(null)
```

So I still need to figre out how to perform this in 1 transaction. This `.transact` method is incorrect

**Comment by armanbilge** [comment]
> Because `*>` is not an atomic combinator, this can lead to transactions nesting, right? I didn't expect to see that on a single threaded environment, but here we are.

Because even in a single-threaded environment, concurrently running fibers can be interleaved with each other. If you need atomicity you should guard your db with `Mutex`.

Even better would be a shared/exclusive lock: acquire a shared lock for ordinary interactions with the db, and acquire an exclusive lock whenever you need to do a transaction.
